// Generated by the Maven Archetype Plug-in
package br.com.doit.boleto.app;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession
{
	private static final long serialVersionUID = 1L;

	public Session()
	{
		super();

		throw new IllegalAccessError("Uma sess\u00e3o n\u00e3o deveria ser criada nesta aplica\u00e7\u00e3o");
	}
}
