// Generated by the Maven Archetype Plug-in
package br.com.doit.pontofrio.app;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
	private static final long serialVersionUID = 1L;

	public Session() {
		super();
	}
}
