name: Deploy
on:
  push:
    branches:
      - master
      - staging
    tags-ignore:
      - woboleto-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout woboleto source code
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy snapshots with Maven
        run: mvn -B -U deploy --file pom.xml -s .maven-settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
