name: Pull Request Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout woboleto source code
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Test with Maven
        run: mvn -B  -U package --file pom.xml -s .maven-settings.xml -DtrimStackTrace=false
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
